// <auto-generated />
using System;
using MachineMonitoring.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineMonitoring.Api.Migrations
{
    [DbContext(typeof(MachineMonitoringDbContext))]
    [Migration("20251226054101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("MachineMonitoring.Api.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Machine_Name_Unique");

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CNC - 01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CNC - 02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MILLING - 01"
                        },
                        new
                        {
                            Id = 4,
                            Name = "MILLING - 02"
                        },
                        new
                        {
                            Id = 5,
                            Name = "PRESS - 01"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PRESS - 02"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ASSEMBLY - 01"
                        });
                });

            modelBuilder.Entity("MachineMonitoring.Api.Models.MachineLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProducedPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LogTime")
                        .HasDatabaseName("IX_MachineLogs_LogTime");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("IX_MachineLogs_MachineId");

                    b.HasIndex("OperatorId");

                    b.ToTable("MachineLogs");
                });

            modelBuilder.Entity("MachineMonitoring.Api.Models.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Operator_Name_Unique");

                    b.ToTable("Operators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jhon Doe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("MachineMonitoring.Api.Models.MachineLog", b =>
                {
                    b.HasOne("MachineMonitoring.Api.Models.Machine", "Machine")
                        .WithMany("MachineLogs")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Api.Models.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.Navigation("Machine");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("MachineMonitoring.Api.Models.Machine", b =>
                {
                    b.Navigation("MachineLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
